"""Programmatic applicant generator for the M2 sim (doc-18 §5).

Each session gets a fresh, randomly-generated applicant + a behavioral style.
This replaces v1's fixed personas (the R12 memorization source): unbounded
unique values mean no string recurs often enough to be memorized, and it gives
us the ground truth to check the harness's extraction against.
"""
from __future__ import annotations
import random

from .schema import Schema

FIRST = ["Maria", "Jordan", "Wei", "Aisha", "Diego", "Priya", "Liam", "Sofia",
         "Kenji", "Fatima", "Noah", "Ananya", "Mateo", "Yuki", "Omar", "Elena",
         "Tariq", "Mei", "Lucas", "Zara", "Ravi", "Chloe", "Samuel", "Nadia"]
LAST = ["Garcia", "Lee", "Chen", "Okafor", "Rossi", "Patel", "Nguyen", "Haddad",
        "Kim", "Silva", "Müller", "Johansson", "Ali", "Tanaka", "Costa", "Novak",
        "Reyes", "Khan", "Andersson", "Mbeki", "Schmidt", "Dubois", "Yamamoto"]
STREETS = ["Maple Ave", "Oak St", "Birch Ln", "Elm Rd", "Cedar Blvd", "Pine Way", "Sunset Dr"]
CITIES = ["Springfield", "Riverton", "Fairview", "Greenville", "Madison", "Clayton", "Auburn"]
USTATES = ["IL", "CA", "NY", "TX", "WA", "MA", "OH", "GA"]

STYLES = ["terse", "chatty", "unsure", "impatient", "polite"]


def gen_style(rng: random.Random) -> str:
    return rng.choice(STYLES)


def gen_persona(schema: Schema, rng: random.Random) -> dict:
    """A complete, diverse applicant. Free fields are generated by type; choice
    fields draw a random option value from the schema."""
    first, last = rng.choice(FIRST), rng.choice(LAST)
    data: dict = {
        "full_name": f"{first} {last}",
        "preferred_name": first,
        "email": f"{first.lower()}.{last.lower()}{rng.randint(1, 99)}@example.com",
        "dob": f"{rng.randint(1985, 2004)}-{rng.randint(1, 12):02d}-{rng.randint(1, 28):02d}",
        "phone": f"({rng.randint(200, 989)}) 555-{rng.randint(1000, 9999)}",
        "mailing_address": f"{rng.randint(1, 9999)} {rng.choice(STREETS)}, "
                           f"{rng.choice(CITIES)}, {rng.choice(USTATES)} {rng.randint(10000, 99999)}",
    }
    for f in schema.fields:
        if f.field_id in data:
            continue
        if f.is_choice:
            data[f.field_id] = rng.choice(f.options)[0]
        elif f.type == "number" and f.min is not None and f.max is not None:
            data[f.field_id] = rng.randint(int(f.min), int(f.max))
    return data
